# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_mainshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainshow',
            name='img',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='img1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='img2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='img3',
            field=models.CharField(max_length=100),
        ),
    ]
